name: Publish DAT Tables

on:
  push:
    tags:
     - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-create: true
          virtualenvs-in-project: true

      - run: poetry install --no-interaction

      - run: make write-generated-tables

      - run: make test

      - name: Bundle tables
        run: tar -czvf deltalake-dat-${{ github.ref_name }}.tar.gz out

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: deltalake-dat-${{ github.ref_name }}.tar.gz
